import { createClient } from '@supabase/supabase-js';
import { projectId, publicAnonKey } from '../../../utils/supabase/info';

// Prioritize environment variables, but use autogenerated metadata as fallbacks
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || `https://${projectId}.supabase.co`;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || publicAnonKey;

// Error prevention in case both are missing (though info.tsx should have them)
if (!supabaseUrl || (supabaseUrl === 'https://undefined.supabase.co')) {
  console.error('[Supabase] CRITICAL ERROR: supabaseUrl is missing.');
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);
